const express = require('express')
const router = express.Router()
const {addCategory,fetchCategory,fetchSingle,updateSingle,deleteSingle} = require('../controller/category')
const auth = require('../middleware/auth')
router.post('/category',auth,addCategory)
router.get('/category',auth,fetchCategory)
router.get('/category/:id',auth,fetchSingle)
router.patch('/category/:id',auth,updateSingle)
router.delete('/category/:id',auth,deleteSingle)
module.exports = router